ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-slim
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS dev-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --dev --frozen-lockfile

FROM base AS dev
COPY --from=dev-deps /app/node_modules /app/node_modules
COPY . .
ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT
CMD [ "pnpm", "run", "dev" ]