ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-slim
LABEL "dev.ethanchang.maintainer"="Ethan Chang"
LABEL "dev.ethanchang.project"="Mockomatic"
LABEL version="0.1.0"

RUN useradd -ms /bin/bash -u 1001 app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
USER app
WORKDIR /app_env

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
COPY --chown=app:app . .

ARG PORT=3000
ENV PORT=$NUXT_PORT
EXPOSE $NUXT_PORT
CMD [ "pnpm", "run", "dev" ]