version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt_frontend
    expose:
      - "3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rust_backend
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
      image: postgres:16
      restart: always
      container_name: postgres_db
      expose:
        - "5432"
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=mydb
      healthcheck:
        test: ["CMD", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - nginx
    networks:
      - app-network
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}  # .env file or Github Actions

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: