FROM rust:1.82.0 AS dev
RUN cargo install cargo-watch
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build
RUN rm -rf src
COPY . .
ARG PORT=8080
ENV PORT=$RUST_PORT
EXPOSE $RUST_PORT
CMD ["cargo", "watch", "-x", "run"]
