FROM rust:1.82.0 AS dev
RUN cargo install cargo-watch
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build
RUN rm -rf src
COPY . .
EXPOSE 8080
CMD ["cargo", "watch", "-x", "run"]